### ISSUE TITLE
Status UI Bug

### ISSUE THREAD

**Issue by AprupKale** [AY2324S1-CS2103T-W17-2/tp#107]
![Screenshot 2023-10-31 210023](https://github.com/AY2324S1-CS2103T-W17-2/tp/assets/69034878/e03eb096-9687-4b00-99ec-2c80709c5bc4)

On entering the status in small-case, the tag in the list view becomes one default color for all possible values, instead of the command being case insensitive and having the same color for `pending` and `Pending`, or `accepted` and `Accepted`, and so on

**Comment by tyouwei** [comment]
Fixed this issue in PR #105
