### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by tim-pipi** [AY2324S1-CS2103T-W17-2/tp#116]
The initial size seems a bit small when a user first runs the jar file.
![image](https://github.com/AY2324S1-CS2103T-W17-2/tp/assets/107602488/e2ed4b53-a081-44eb-bd6c-e7d26e5e2a08)

The above is an example!

**Comment by tyouwei** [comment]
Noted, I'll fix this either over the weekend or tonight
