### ISSUE TITLE
[PE-D][Tester B] Improvement for undo commands

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W17-2/tp#128]
When `undo` a deletion on certain row in note,  

![image.png](https://raw.githubusercontent.com/WangCheng0116/ped/main/files/f20906ef-743f-4a3b-9518-2c007b9ac5bf.png)  
The application won't show the specific details of the `undo` object, instead, it displays nothing. It will be better to show the full details of the modified object, reducing the hassle for users to navigate back to object again.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: WangCheng0116/ped#4

**Comment by zhengyup** [comment]
Agreed on this! It would help to give greater clarity to the user on what has happened.

**Comment by zhengyup** [comment]
Feature Flaw and not Bug
