### ISSUE TITLE
[PE-D][Tester D] Note command allows multiple inputs

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W17-2/tp#133]
For note INDEX I/NOTE command, the application allows "note 1 i/a i/b i/s". Not sure what the intended behavior is.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: lyuanww/ped#5

**Comment by tyouwei** [comment]
Same Bug Report Issue as #139
