### ISSUE TITLE
[PE-D][Tester E] Default sorting order should be in inverse order

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W17-2/tp#143]
As mentioned in the previous issue, perhaps it would be good to have the default display also be in inverted order, so that users do not need to scroll down the list to view their most recent applications.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: ruiyangzh/ped#7

**Comment by tyouwei** [comment]
Not sure if this would violate the rule of not adding feature, we should check with Yue Ran for this

**Comment by tyouwei** [comment]
Closing feature suggestions
