### ISSUE TITLE
[PE-D][Tester C] Lack of Outline in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W17-2/tp#150]
There is no outline in UG. Users fail to quickly access the command he or she wants to check.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: li-rongzhi/ped#5

**Comment by tim-pipi** [comment]
I found that this is due to the screen size being too small. Although the user can just click the triple dot icon to open it.
