### ISSUE TITLE
[PE-D][Tester E] Undo command without corresponding redo command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W17-2/tp#158]
As mentioned. Since you have to store previous states anyways to implement the undo command, implementation of redo should be doable without excessive effort.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: ruiyangzh/ped#10

**Comment by tyouwei** [comment]
Not sure if this would violate the rule of not adding feature, we should check with Yue Ran for this

**Comment by zhengyup** [comment]
To me, undo helps to mitigate the destructiveness of commands like Undo and Clear, which would be useful especially to new users. This makes the implementation simpler than having to do a redo command. Though redo is definitely a nice feature to have, the utility did not justify the time spent for implementation.

**Comment by tyouwei** [comment]
Closing feature suggestions
